export const SET_USERS = 'set_users'
export const SET_MATTERS = 'set_matters'
export const SET_TYPE_SERVICES = 'set_type_services'
export const SET_SERVICES = 'set_services'
export const SET_QUOTES = 'set_quotes'
export const SET_QUOTE_BY_ID = 'set_quote_by_id'
export const SET_TIME_PAY = 'set_time_pay'
export const SET_TYPE_APPOINTMENT = 'set_type_appointment'
